function install_aide {
  apt-get install aide -y
  aideinit
  cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db
  update-aide.conf
  cp /var/lib/aide/aide.conf.autogenerated /etc/aide/aide.conf
}

function c_1_3 {
  log_info "Started hardening section 1.3: File Integrity Check"
  install_aide

  initctl reload-configuration
}
